#!/usr/bin/env python3
# Auto-generated by Hermes Agent
# Generates .list files + surge.conf from raw blackmatrix7 rules
import os, re, json
from collections import defaultdict, Counter

DOWNLOAD_DIR = "/tmp/surge-refresh"
OUTPUT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RULES_DIR = os.path.join(OUTPUT_DIR, "rules")
os.makedirs(RULES_DIR, exist_ok=True)

# Parse all .list files in download dir
expanded = []
for fname in os.listdir(DOWNLOAD_DIR):
    fpath = os.path.join(DOWNLOAD_DIR, fname)
    if not fname.endswith(".list") or not os.path.isfile(fpath):
        continue
    with open(fpath, "r", encoding="utf-8", errors="replace") as f:
        content = f.read()
    for line in content.strip().split("\n"):
        s = line.strip()
        if not s or s.startswith("#") or s.startswith("//"):
            continue
        parts = s.split(",")
        if len(parts) >= 2:
            expanded.append({
                "type": parts[0].strip(),
                "value": parts[1].strip(),
                "file": fname
            })

print(f"Total expanded rules: {len(expanded)}")

# Deduplicate
seen = {}
deduped = []
for r in expanded:
    key = (r["type"], r["value"])
    if key not in seen:
        seen[key] = r
        deduped.append(r)

print(f"After dedup: {len(deduped)}")

# Group rules (no policy splitting - let surge.conf handle policies)
# Write combined files by rule type
with open(os.path.join(OUTPUT_DIR, "surge.conf"), "w") as f:
    f.write("[Rule]\n")
    for r in deduped:
        f.write(f"{r['type']},{r['value']}\n")

print("Done!")
